// UI — TUI components, formatters, event mappers.

export type {
	ConversationLine,
	ConversationRegion,
	HeaderRegion,
	LayoutAccumulator,
	StatusLineRegion,
	ToolCallDisplayStatus,
	TuiScreenLayout,
} from "./adapters/index.js";

import {
	ansiClearBelow,
	ansiClearLine,
	ansiCursorHome,
	ansiDisableFocusReporting,
	ansiDisableMouseTracking,
	ansiEnableFocusReporting,
	ansiEnableMouseTracking,
	ansiEnterAlternateScreen,
	ansiExitAlternateScreen,
	ansiHideCursor,
	ansiMoveLeft,
	ansiMoveRight,
	ansiMoveUp,
	ansiResetCursor,
	ansiRestoreCursor,
	ansiSaveCursor,
	ansiShowCursor,
	createLayoutAccumulator,
	renderHeader,
	renderScreen,
	renderStatusLine,
} from "./adapters/index.js";

// Legacy TUI/ANSI compatibility namespace.
// New call sites should prefer app-tui-core and keep this surface read-only.
export const legacyTuiCompat = {
	ansiClearBelow,
	ansiClearLine,
	ansiCursorHome,
	ansiDisableFocusReporting,
	ansiDisableMouseTracking,
	ansiEnableFocusReporting,
	ansiEnableMouseTracking,
	ansiEnterAlternateScreen,
	ansiExitAlternateScreen,
	ansiHideCursor,
	ansiMoveLeft,
	ansiMoveRight,
	ansiMoveUp,
	ansiResetCursor,
	ansiRestoreCursor,
	ansiSaveCursor,
	ansiShowCursor,
	createLayoutAccumulator,
	renderHeader,
	renderScreen,
	renderStatusLine,
} as const;
export type {
	InteractiveLocalCommandDeps,
	SlashCommandRegistry,
	SlashCommandResolution,
} from "./domain/index.js";
// Domain (slash commands)
export {
	createBuiltinCommandRegistry,
	createBuiltinCommands,
	createInteractiveCommandRegistry,
	createInteractiveLocalCommands,
	createSlashCommandRegistry,
	renderWorkingTreeSummary,
} from "./domain/index.js";
// Services (formatters + interaction state)
export {
	beginResumeBrowserOverlaySearch,
	appendAssistantTranscriptBlock,
	appendTranscriptBlockWithSpacer,
	beginResumeBrowserSearch,
	clearPendingPermissionRequest,
	buildInteractiveFooterLeadingLines,
	buildRestoredContextLines,
	buildResumeBrowserBodyBlocks,
	buildResumeBrowserFooterHintLines,
	buildResumeBrowserHeaderLines,
	buildResumeBrowserResumedLines,
	completeResumeBrowserSearch,
	computeInteractiveFooterSeparatorWidth,
	createInteractiveConversationState,
	createResumeBrowserState,
	closeResumeBrowserOverlay,
	createRpcError,
	createRpcResponse,
	eventToJsonEnvelope,
	eventToRpcNotification,
	formatEventAsText,
	formatFullWidthTranscriptUserLine,
	formatInteractiveErrorDetailLine,
	formatInteractiveErrorLine,
	formatInteractiveInfoLine,
	formatInteractiveInputSeparator,
	formatInteractivePromptBuffer,
	formatPermissionPrompt,
	formatPlanSummaryText,
	formatResumeBrowserTranscriptBlocks,
	formatToolStep,
	formatTranscriptAssistantLine,
	formatTranscriptUserBlocks,
	formatTranscriptUserLine,
	formatTurnNotice,
	INTERACTIVE_THEME,
	initialInteractionState,
	initialInteractiveOverlayState,
	materializeAssistantTranscriptBlock,
	markResumeBrowserSubmitPending,
	measureResumeBrowserSelectedLineOffset,
	mergeStreamingText,
	movePendingPermissionSelection,
	moveResumeBrowserSelection,
	moveResumeBrowserOverlaySelection,
	openResumeBrowserOverlay,
	parseRpcRequest,
	RPC_ERRORS,
	RPC_METHODS,
	reduceInteractionState,
	resetInteractiveOverlayState,
	resolveRecentSessionDirectSelection,
	resolveResumeBrowserKeyAction,
	resolveResumeBrowserSelectedIndex,
	resolveResumeBrowserSubmitHit,
	setPendingPermissionRequest,
	completeResumeBrowserOverlaySearch,
	sanitizeForJson,
	toggleResumeBrowserOverlayPreview,
	summarizeResumeBrowserHit,
	toggleResumeBrowserPreviewState,
} from "./services/index.js";
// Types
export type {
	InteractionPhase,
	InteractionState,
	InteractiveOverlayState,
	JsonEnvelope,
	ModelOption,
	OutputMode,
	OutputSink,
	PendingPermissionDetails,
	PendingPermissionState,
	RenderContext,
	ResumeBrowserState,
	RpcEnvelope,
	SlashCommand,
	SlashCommandContext,
	SlashCommandHost,
	SlashCommandResult,
	SlashCommandType,
} from "./types/index.js";
